"""Replay the known-answer vectors hcfs exports.

hcfs is the oracle. Every case here compares this SDK's output against bytes a
Rust test produced, so a divergence fails in Python before it reaches a user's
files. The file is absent until Phase 0 lands the exporter in hcfs; see
tests/vectors/README.md for the interim oracle and the expected schema.
"""

import base64
import json
from pathlib import Path
from typing import Any

import pytest

from hippius_drive.crypto import file_cipher, hashes, kdf, mnemonic_blob, mnemonic_store
from hippius_drive.identity import Identity, rename_text, tos_text

VECTORS_PATH = Path(__file__).parent / "vectors" / "hcfs-vectors-v1.json"

if not VECTORS_PATH.exists():
    pytest.skip(
        f"{VECTORS_PATH.name} is not committed yet; it is generated by "
        "hcfs-client/tests/export_sdk_vectors.rs (hcfs Phase 0 Task 0.3). "
        "See tests/vectors/README.md for the interim oracle.",
        allow_module_level=True,
    )

VECTORS: dict[str, Any] = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))


def test_vector_file_is_version_one() -> None:
    assert VECTORS["version"] == 1


@pytest.mark.parametrize("v", VECTORS["derivation"], ids=lambda v: str(v["label"]))
def test_derivation(v: dict[str, Any]) -> None:
    folder = kdf.derive_folder_mnemonic(VECTORS["master_mnemonic"], v["label"])
    assert folder == v["folder_mnemonic"]
    assert kdf.folder_hash(v["label"]) == v["folder_hash"]

    keys = kdf.folder_keys(folder)
    assert keys.signing_seed.hex() == v["signing_key_hex"]
    assert keys.encryption_key.hex() == v["encryption_key_hex"]

    ident = Identity.from_folder_mnemonic(folder, v["label"], account_ss58=VECTORS["account_ss58"])
    assert ident.verifying_key.hex() == v["verifying_key_hex"]
    assert ident.folder_hash == v["folder_hash"]


@pytest.mark.parametrize("v", VECTORS["cipher"], ids=lambda v: str(v["plaintext_len"]))
def test_cipher_blob_is_byte_identical(v: dict[str, Any]) -> None:
    key = bytes.fromhex(v["key_hex"])
    plaintext = bytes.fromhex(v["plaintext_hex"])
    assert len(plaintext) == v["plaintext_len"]

    base_nonce = bytes.fromhex(VECTORS["base_nonce_hex"])
    blob = file_cipher.encrypt_bytes(plaintext, key, base_nonce=base_nonce)

    assert blob.hex() == v["ciphertext_hex"]
    assert hashes.blake3_hex(blob) == v["ciphertext_hash"]
    assert len(blob) == file_cipher.ciphertext_size(v["plaintext_len"])
    assert file_cipher.decrypt_bytes(blob, key) == plaintext


def test_hashes() -> None:
    v = VECTORS["hashes"]
    assert hashes.path_hash(v["path"]).hex() == v["path_hash"]
    salted = hashes.salted_hash(VECTORS["account_ss58"], bytes.fromhex(v["salted_plaintext_hex"]))
    assert salted.hex() == v["salted_hash"]


def test_manifest_signature_and_fields() -> None:
    v = VECTORS["manifest"]
    expected = v["manifest"]
    ident = Identity.from_folder_mnemonic(
        VECTORS["derivation"][0]["folder_mnemonic"],
        VECTORS["derivation"][0]["label"],
        account_ss58=VECTORS["account_ss58"],
    )
    key = bytes.fromhex(v["key_hex"])
    plaintext = bytes.fromhex(v["plaintext_hex"])
    base_nonce = bytes.fromhex(VECTORS["base_nonce_hex"])
    blob = file_cipher.encrypt_bytes(plaintext, key, base_nonce=base_nonce)
    ciphertext_hash = hashes.blake3_hex(blob)

    assert ciphertext_hash == expected["ciphertext_hash"]
    assert tos_text(ciphertext_hash) == v["tos_text"]
    # Ed25519 is deterministic, so the signature bytes themselves are pinned.
    assert list(ident.sign_ciphertext_hash(ciphertext_hash)) == expected["signature"]
    assert list(ident.verifying_key) == expected["signing_key"]
    assert list(hashes.path_hash(v["relative_path"])) == expected["path_hash"]
    assert expected["ss58_address"] == VECTORS["account_ss58"]
    assert expected["size_bytes"] == len(plaintext)
    assert expected["timestamp"] == v["timestamp"]
    assert expected["revision_seq"] == v["revision_seq"]
    assert expected["base_revision_id"] is None


@pytest.mark.parametrize(
    "v", VECTORS["mnemonic_store"], ids=lambda v: f"{v['iterations']}-iterations"
)
def test_mnemonic_store_vectors(v: dict[str, Any], tmp_path: Path) -> None:
    path = tmp_path / "enc_mnemonic.json"
    path.write_text(json.dumps(v["file"]), encoding="utf-8")
    assert mnemonic_store.load(path, v["password"]) == v["mnemonic"]

    # Re-sealing with the vector's own salt and IV must reproduce it byte for byte.
    rewritten = tmp_path / "rewritten.json"
    mnemonic_store.save_with(
        rewritten,
        v["mnemonic"],
        v["password"],
        mnemonic_store.StoreParams(
            salt=base64.b64decode(v["salt_b64"]),
            iv=base64.b64decode(v["iv_b64"]),
            iterations=v["iterations"],
        ),
    )
    assert json.loads(rewritten.read_text(encoding="utf-8")) == v["file"]


def test_mnemonic_blob_vector() -> None:
    v = VECTORS["mnemonic_blob"]
    blob = mnemonic_blob.SealedBlob.model_validate(v["blob"])
    assert mnemonic_blob.open_blob(blob, v["passphrase"], VECTORS["account_ss58"]) == v["mnemonic"]

    resealed = mnemonic_blob.seal_with(
        v["mnemonic"],
        v["passphrase"],
        VECTORS["account_ss58"],
        mnemonic_blob.SealInputs(
            salt=base64.b64decode(v["salt_b64"]),
            nonce=base64.b64decode(v["nonce_b64"]),
            kdf=mnemonic_blob.KdfParams.model_validate(v["kdf"]),
        ),
    )
    assert resealed.model_dump() == blob.model_dump()


def test_rename_text() -> None:
    v = VECTORS["rename_text"]
    pairs = [(bytes.fromhex(p["old_hex"]), bytes.fromhex(p["new_hex"])) for p in v["pairs"]]
    assert rename_text(pairs) == v["text"]
